web-noter/noter/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

APIPatterns = [
	url(r'^getNotes/$', 'note.api.API_getNotes', name="getNotes"),
	url(r'^rmNote/$', 'note.api.API_rmNote', name="rmNote"),
	url(r'^rmNotes/$', 'note.api.API_rmNotes', name="rmNotes"),
	url(r'^register/$', 'note.api.API_register', name="register"),
	url(r'^addNote/$', 'note.api.API_addNote', name="addNote"),
	url(r'^addNotes/$', 'note.api.API_addNotes', name="addNotes"),
	url(r'^deleteAccount/$', 'note.api.API_deleteAccount', name="deleteAccount"),
	url(r'^getNote/$', 'note.api.API_getNote', name="getNote"),
	url(r'^getUserInfo/$', 'note.api.API_getUserInfo', name="getUserInfo"),
	url(r'^updateUsername/$', 'note.api.API_update_username', name="updateUsername"),
	url(r'^updateFirstName/$', 'note.api.API_update_first_name', name="updateFirstName"),
	url(r'^updateLastName/$', 'note.api.API_update_last_name', name="updateLastName"),
	url(r'^updateEmail/$', 'note.api.API_update_email', name="updateEmail"),
	url(r'^updatePassword/$', 'note.api.API_update_password', name="updatePassword"),
	url(r'^editNote/$', 'note.api.API_edit_note', name="editNote"),
	url(r'^similiar/$', 'note.api.API_find_similiar', name="similiar"),
]

urlpatterns = patterns('',
	
	url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^(?P<page_number>\d*)$', 'note.views.home', name="Home"),
	url(r'^note/(?P<note_id>\d+)/$', 'note.views.get_note', name="getNote"),
	url(r'^addnote/$', 'note.ajax.add_note', name="addNote"),
	url(r'^add/$', 'note.views.add_note_page', name="Add"),
	url(r'^remove/$', 'note.ajax.remove_note', name="rmNote"),
	url(r'^manage/(?P<page_number>\d*)$', 'note.views.manage_notes', name="Manage"),
	url(r'^edit/(?P<note_id>\d+)/$', 'note.views.edit', name="Edit"),
	url(r'^update/$', 'note.ajax.update', name="Update"),
	url(r'^search/(?P<query>.*)/(?P<page_number>\d+)/$', 'note.views.search'),
	url(r'^search/(?P<query>.*)/$', 'note.views.search', name="Search"),
	url(r'^suggestedtags/$', 'note.ajax.check_similarity_ajax', name="checkSimilarityAjax"),
	url(r'^filter/(?P<page_number>\d+)/$', 'note.views.filter_all_notes'),
	url(r'^filter/(?P<tags>.+)/(?P<page_number>\d+)/$', 'note.views.filter_all_notes'),
	url(r'^filter/(?P<tags>.+)/$', 'note.views.filter_all_notes'),
	url(r'^filter/$', 'note.views.filter_all_notes', name="filter"),
	url(r'^filterdone/(?P<page_number>\d+)/$', 'note.views.filter_done'),
	url(r'^filterdone/(?P<tags>.+)/(?P<page_number>\d+)/$', 'note.views.filter_done'),
	url(r'^filterdone/(?P<tags>.+)/$', 'note.views.filter_done'),
	url(r'^filterdone/$', 'note.views.filter_done', name="filterDone"),
	url(r'^filterundone/(?P<page_number>\d+)/$', 'note.views.filter_undone'),
	url(r'^filterundone/(?P<tags>.+)/(?P<page_number>\d+)/$', 'note.views.filter_undone'),
	url(r'^filterundone/(?P<tags>.+)/$', 'note.views.filter_undone'),
	url(r'^filterundone/$', 'note.views.filter_undone', name="filterUndone"),
	url(r'^filtersnippets/(?P<page_number>\d+)/$', 'note.views.filter_snippets'),
	url(r'^filtersnippets/(?P<tags>.+)/(?P<page_number>\d+)/$', 'note.views.filter_snippets'),
	url(r'^filtersnippets/(?P<tags>.+)/$', 'note.views.filter_snippets'),
	url(r'^filtersnippets/$', 'note.views.filter_snippets', name="filterSnippets"),
	url(r'^filterwarnings/(?P<page_number>\d+)/$', 'note.views.filter_warnings'),
	url(r'^filterwarnings/(?P<tags>.+)/(?P<page_number>\d+)/$', 'note.views.filter_warnings'),
	url(r'^filterwarnings/(?P<tags>.+)/$', 'note.views.filter_warnings'),
	url(r'^filterwarnings/$', 'note.views.filter_warnings', name="filterWarnings"),
	url(r'^filternotes/(?P<page_number>\d+)/$', 'note.views.filter_notes'),
	url(r'^filternotes/(?P<tags>.+)/(?P<page_number>\d+)/$', 'note.views.filter_notes'),
	url(r'^filternotes/(?P<tags>.+)/$', 'note.views.filter_notes'),
	url(r'^filternotes/$', 'note.views.filter_notes', name="fitlerNotes"),
	url(r'^contact/$', 'note.views.contact', name="Contact"),
	url(r'^about/$', TemplateView.as_view(template_name="about.html"), name="About"),
	url(r'^login/$', 'note.views.login_view', name="Login"),
	url(r'^logout/$', 'note.views.logout_view', name="Logout"),
	url(r'^register/$', 'note.views.register', name="Register"),
	url(r'^profile/$', 'note.views.profile', name="Profile"),
	url(r'^update-username/$', 'note.ajax.update_username', name="updateUsername"),
	url(r'^update-password/$', 'note.ajax.update_password', name="updatePassword"),
	url(r'^update-firstname/$', 'note.ajax.update_first_name', name="updateFirstName"),
	url(r'^update-lastname/$', 'note.ajax.update_last_name', name="updateLastName"),
	url(r'^delete-account/$', 'note.views.delete_account', name="deleteAccount"),
	url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'note.views.reset_password_confirm', name="password_reset_confirm"),
	url(r'^reset/$', 'note.views.reset_password', name="password_reset"),
	url(r'^reset/complete/$', TemplateView.as_view(template_name="registration/password_reset_complete.html")),
	url(r'^reset/sent/$', TemplateView.as_view(template_name="registration/password_reset_sent.html")),
	url(r'^api/', include(APIPatterns, namespace="API")),
	url(r'^api-info/$', TemplateView.as_view(template_name="api-info.html")),
	url(r'^similiar/(?P<note_id>\d+)/(?P<page_number>\d*)$', 'note.views.find_similiar_notes', name="Similiar"),
)

web-noter/note/models.py
from django.db import models

from django.conf import settings

import sys, re

def replace_newlines_string(string):
	"""Replace all the newlines (\n) by <br/> in a string"""
	
	text = ""
	text_splitted = string.split("\n")
	length = len(text_splitted)
	i = 0
	
	for line in text_splitted:
		i += 1
		line = line.replace("\t", "&nbsp;&nbsp;&nbsp;&nbsp;")
		text += line
		
		if i < length: # Check if it's last line:
			if not re.search("<.*?>$", line):
				text += "<br/>"
			text += "\n"
		
	return text

class Note(models.Model):
	title = models.CharField(max_length=100)
	text = models.TextField()
	tags = models.TextField()
	type = models.CharField(max_length=50, choices=(
		("n", "Note"),
		("s", "Snippet"),
		("t", "Todo"),
		("w", "Warning")
	), default="n")
	is_checked = models.BooleanField(default=False)
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	date = models.DateTimeField(auto_now_add=True)
	
	def no_html(self):
		if self.type != "s":
			return re.sub("<.*?>", "", self.text)
		else:
			return self.text
	
	def getTags(self):
		tags = self.tags.split(",")
		for i in range(len(tags)):
			if tags[i].startswith(" "):
				tags[i] = tags[i][1:]
		return tags
	
	def replaceNewLines(self):
		if self.type != "s":
			return replace_newlines_string(self.text)
		else:
			return self.text
	
	class Meta:
		ordering = ["-date"]
	if sys.version_info.major > 2:
		def __str__(self):
			return self.title
	else:
		def __unicode__(self):
			return self.title
	
	def save(self, *args, **kwargs):
		r1 = re.compile("<[ \t]*script[ \t]*.*?>.*<[ \t]*/[ \t]*script[ \t]*>", re.I)
		r2 = re.compile("<[ \t]*script[ \t]*.*?>.*", re.I)
		self.text = re.sub(r1, "", self.text)
		self.text = re.sub(r2, "", self.text)
		super(Note, self).save(*args, **kwargs)

web-noter/note/views.py
"""
@author: Ivan Konovalov

Views for Noter, Django site
"""

from django.shortcuts import render_to_response, redirect

from django.http import Http404, HttpResponse

from note.models import Note

from django.core.paginator import Paginator, EmptyPage

from django.core.exceptions import ObjectDoesNotExist

from django.db.models import Q

from django.template import RequestContext

from django.contrib.auth import login, logout, authenticate

from django.contrib.auth.views import password_reset, password_reset_confirm

from django.contrib.auth.models import User

from django.core.mail import send_mail

from note.functions import check_similarity, transform_tags_sim

from note.functions import htmlbody, place_by_relevance

from note.functions import page_range

from note.functions import transform_tags_single

from note.functions import replace_newlines_sim

def requires_authentication(view):
	def wrapper(request, *args, **kwargs):
		if not request.user.is_authenticated(): # If user is not logged in
			return redirect('/login?return={}'.format(request.path))
		
		return view(request, *args, **kwargs)
	
	return wrapper

@requires_authentication
def home(request, page_number=1):
	"""Home page"""
	
	try:
		page_number = int(page_number)
	except ValueError:
		page_number = 1

	notes = Note.objects.filter(author=request.user.id) # Get all the notes
	
	paginator = Paginator(notes, 10) # Split into pages
	
	if page_number > paginator.num_pages:
		raise Http404
	
	current_page = paginator.page(page_number)
	prange = page_range( # Generate page range
		page_number,
		paginator.num_pages
	)
	context = {
		"notes": current_page, # Content of current page
		"current_page_number": page_number, # Current page number
		"num_pages": paginator.num_pages, # Number of pages
		"page_range": prange # Pages that will be displayed
	}
	return render_to_response("home.html", context) # Render page

@requires_authentication
def get_note(request, note_id):
	"""Get Note by id. It's a page"""
	
	try: # Sometimes there's no such note
		note = Note.objects.get(author=request.user.id, id=note_id)
	except ObjectDoesNotExist: # Sometimes note may not exist
		raise Http404 # Display '404 Not Found' error
	
	try: # Sometimes note can be latest
		next_note = note.get_next_by_date( # Get next note
			author=request.user.id
		)
	except ObjectDoesNotExist: # If there's no next note
		next_note = None # Next note will be None
	
	try: # Sometimes note can be first
		previous_note = note.get_previous_by_date( # Get previous note
			author=request.user.id
		)
	except ObjectDoesNotExist: # If there's no previous note
		previous_note = None # Previous note will be None
	
	context = {
		"note": note, # Note object
		"next": next_note, # Next note object
		"previous": previous_note # Previous note object
	}
	return render_to_response("note.html", context) # Render page

@requires_authentication
def add_note_page(request):
	"""Add note page"""

	return render_to_response(
		"add_note.html",
		{},
		context_instance=RequestContext(request)
	)

@requires_authentication
def manage_notes(request, page_number=1):
	"""Manage notes"""
	
	try:
		page_number = int(page_number)
	except ValueError: # If page number is not set
		page_number = 1 # Go to the first page
	
	notes = Note.objects.filter(author=request.user.id) # Get all the notes
	paginator = Paginator(notes, 10) # Split notes into pages
	
	try: # Page number can be too big
		current_page = paginator.page(page_number)
	except EmptyPage: # If page number is too big
		raise Http404 # Display '404 Not Found' error
	
	prange = page_range( # Generate page range
		page_number,
		paginator.num_pages)
	
	context = {
		"notes": current_page, # Current page content
		"current_page_number": page_number, # Current page number
		"num_pages": paginator.num_pages, # Number of pages
		"page_range": prange # Page range
	}
	
	return render_to_response("manage.html", context) # Render page

@requires_authentication
def edit(request, note_id):
	"""Edit note. It's a page"""
	
	try: # Sometimes we confuse the digit with a string
		note_id = int(note_id) # Convert string into integer
		try: # Sometimes we request something that doesn't exist
			note = Note.objects.get( # Get note from database
				author=request.user,
				id=note_id
			)
		except ObjectDoesNotExist: # If note doesn't exist
			raise Http404
	except TypeError: # If somebody confused the digit with the string
		raise Http404 # I will raise the great '404 Not Found' error!
	
	similiar = check_similarity(note)[0:3] # Top 3 similiar notes
	similiar = transform_tags_sim(similiar) # Split tags into a list
	
	context = {
		"note": note, # Note object
		"similiar": similiar, # Top 3 similiar notes
	}
	
	return render_to_response("edit.html", context) # Render page

@requires_authentication
def search(request, query, page_number=1):
	"""Search for notes"""
	
	context = {"errors": [], "q": query}
	
	# Define error messages
	too_long_error = "Search query cannot contain more than 150 symbols"
	empty_error = "Search query cannot be empty"
	
	if query:
		query = query.lower()
		query_splitted = query.split()
		context["qs"] = query_splitted
		
		if len(query) > 150: # If search query is too long
			context["errors"].append(too_long_error) # Append error
		
		try: # Page number can be invalid
			page_number = int(page_number) # Convert string to integer
		except TypeError: # If page number is invalid
			page_number = 1 # Go to first page
		
	else: # If search query is empty
		context["errors"].append(empty_error) # Append error message
	
	if not context["errors"]: # If there's no errors
		found = []
		sorted_found = [] # Will contain sorted results later
		notes = Note.objects.filter(author=request.user.id)

		for note in notes:
			passing = False
			for i in query_splitted:
				if i in note.no_html().lower() \
				or i in note.title.lower() or i in note.tags.lower():
					if not note in found:
						passing = True
				else:
					passing = False
					break
			
			if passing:
				found.append(note)
				sorted_found.append( # Place by relevance
					place_by_relevance(
						note,
						query_splitted,
						splitted=True,
					lower=True))
			
		sorted_found.sort()	# Sort notes
		
		try: # Page number can be too big
			paginator = Paginator(sorted_found, 10) # Split content into pages
			found = paginator.page(page_number)
		except EmptyPage: # If page number is too big
			raise Http404 # Display '404 Not found' error
		
		prange = page_range( # Generate page range
			page_number,
			paginator.num_pages
		)
		
		# Pack context
		context["found"] = found # Set list with found notes
		context["num_pages"] = paginator.num_pages # Set number of pages
		context["current_page_number"] = page_number # Set current page number
		context["page_range"] = prange # Set page range
		
		return render_to_response("search.html", context)

@requires_authentication
def filter_all_notes(request, tags="", page_number=1):
	"""Filter all the notes"""
	
	context = {}
	context["tags"] = tags
	if tags:
		context["tags"] = tags+"/"
	tags = transform_tags_single(tags)
	
	notes = Note.objects.filter(author=request.user.id)
	filtered = []
	
	for note in notes:
		ntags = note.getTags()
		if tags:
			for tag in tags:
				if tag in ntags:
					have_tag = True
				else:
					have_tag = False
					break
			if have_tag:
				filtered.append(note)
		else:
			filtered.append(note)
	
	try:
		page_number = int(page_number)
	except ValueError:
		page_number = 1
	
	paginator = Paginator(filtered, 10)
	filtered_page = paginator.page(page_number)
	prange = page_range(page_number, paginator.num_pages)

	context["filtered"] = filtered_page
	context["current_page_number"] = page_number
	context["num_pages"] = paginator.num_pages
	context["page_range"] = prange
	context["urlprefix"] = ""

	return render_to_response("filter.html", context)

@requires_authentication
def filter_done(request, tags="", page_number=1):
	"""Filter checked todo notes"""

	context = {}
	context["tags"] = tags
	if tags:
		context["tags"] = tags+"/"
	tags = transform_tags_single(tags)
	
	notes = Note.objects.filter(
		author=request.user.id,
		type="t",
		is_checked=True
	)
	filtered = []
	
	for note in notes:
		ntags = note.getTags()
		if tags:
			for tag in tags:
				if tag in ntags:
					have_tag = True
				else:
					have_tag = False
					break
			if have_tag:
				filtered.append(note)
		else:
			filtered.append(note)
	
	try:
		page_number = int(page_number)
	except ValueError:
		page_number = 1
	
	paginator = Paginator(filtered, 10)
	filtered_page = paginator.page(page_number)
	prange = page_range(page_number, paginator.num_pages)

	context["filtered"] = filtered_page
	context["current_page_number"] = page_number
	context["num_pages"] = paginator.num_pages
	context["page_range"] = prange
	context["urlprefix"] = "done"

	return render_to_response("filter.html", context)

@requires_authentication
def filter_undone(request, tags="", page_number=1):
	"""Filter unchecked todo notes"""

	context = {}
	context["tags"] = tags
	if tags:
		context["tags"] = tags+"/"
	tags = transform_tags_single(tags)
	
	notes = Note.objects.filter(
		author=request.user.id,
		type="t",
		is_checked=False
	)
	filtered = []
	
	for note in notes:
		ntags = note.getTags()
		if tags:
			for tag in tags:
				if tag in ntags:
					have_tag = True
				else:
					have_tag = False
					break
			if have_tag:
				filtered.append(note)
		else:
			filtered.append(note)
	
	try:
		page_number = int(page_number)
	except ValueError:
		page_number = 1
	
	paginator = Paginator(filtered, 10)
	filtered_page = paginator.page(page_number)
	prange = page_range(page_number, paginator.num_pages)

	context["filtered"] = filtered_page
	context["current_page_number"] = page_number
	context["num_pages"] = paginator.num_pages
	context["page_range"] = prange
	context["urlprefix"] = "undone"

	return render_to_response("filter.html", context)

@requires_authentication

web-noter/templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block content %}
	<article class="note">
		<a href="/about/">
			<span class="title">About</span>
		</a>
		<div class="date">Saturday, 12 April 2014 17:04</div>
		<p class="text">
			<h3 id="what-is-noter">What is Noter?</h3>
			<p>
				Noter is an amazing site for keeping notes.<br/>
			</p>
			<h3 id="developers">Who am I?</h3>
			<p>
				My name is Ivan Konovalov (<a href="https://plus.google.com/102869158244616762491">Google+ profile</a>).<br/>
				I'm a programmer.<br/>
				Programming &#8212; is my hobby and I really enjoy it.
			</p>
			<h3 id="why">Why?</h3>
			<p>
				Because there's no perfect tool for keeping notes 
				and Noter is not an exception.<br/>
				But Noter made differently, it has easier UI and it's open source (<a href="https://github.com/SPython/web-noter.git">Repository on Github</a>).
			</p>
			<h3 id="noter-vs-monsters">Noter vs. monsters like Evernote</h3>
			<p>
				I'm not trying to say that monsters like Evernote sucks.<br/>
				I'm just trying to say that Noter is much lighter and it's <strong style="font-size: 18px;">definetly</strong> not a monster.<br/>
				It's easy to use, fully free and simple.<br/>
				And what about our monsters?
				Here's the list:
				<ol>
					<li>Too big</li>
					<li>With limits of free usage</li>
					<li>Too Complicated</li>
				</ol>
			</p>
			<h3 id="history">History</h3>
			<p>
				I've got an idea to create Noter after I got my phone (Huawei U8110) broken.<br/>
				I used to always keep notes, that was a part of my common day. I used ColorNote for Android to do that.<br/>
				But there was so many things...
				I had to write them somewhere.<br/>
				Before it was my phone but what should I do when it's broken?<br/>
				Of course I could write them on paper but that's just inconvenient.<br/>
				So, after some months I decided to create Noter.<br/>
				Because I wanted to create something my own, with my own suggestions, something that I really need right now.
			</p>
		</p>
	</article>
{% endblock %}

web-noter/templates/add_note.html
{% extends "base.html" %}
{% block title %}Add note{% endblock %}
{% block content %}
	<div id="result" class="alert"></div>
	{% csrf_token %}
	<div class="margin-bottom">
		<div class="margin-bottom">
			<label class="label" for="title">Title:</label>
			<input type="text" class="input-field" placeholder="Title" name="title" value="{{ title }}" autocomplete="off" />
		</div>
		<div class="margin-bottom">
			<label class="label" for="text">Text:</label>
			<textarea name="text" id="txt" spellcheck="false" class="textarea-field" rows="13" placeholder="Text" value="{{ text }}"></textarea>
		</div>
		<div class="margin-bottom">
			<div class="suggested-tags"></div>
			<label class="label" for="tags">Tags:</label>
			<input type="text" class="input-field" placeholder="Separate with comma" name="tags" onclick="getTags(-1, $('textarea[name=text]').val(), $('input[name=title]').val())" autocomplete="off" value="{{ tags }}" />
		</div>
		<div class="margin-bottom">
			<label for="note">
				<input type="radio" name="type" value="n" id="note" />
				Note
			</label>
		</div>
		<div class="margin-bottom">
			<label for="todo">
				<input type="radio" name="type" value="t" id="todo" />
				Todo
			</label>
		</div>
		<div class="margin-bottom">
			<label for="snippet">
				<input type="radio" name="type" value="s" id="snippet" />
				Code Snippet
			</label>
			</div>
		<div class="margin-bottom">
			<label for="warning">
				<input type="radio" name="type" value="w" id="warning" />
				Warning
			</label>
		<p>
			<button class="btn-success" onclick="if($('input[name=tags]').val().split(',').length > 10) { alert('Maximum amount of tags is 10.'); return false;} else
{add($('input[name=title]').val(),$('textarea[name=text]').val(),
$('input[name=tags]').val(), findChecked()); return false;}">Save</button>
			<button class="btn-success" type="button" onclick="preview();">Preview</button>
		</p>
		</div>
		<article class="note preview">
			<h2></h2>
			<a>
				<span class="title"></span>
			</a>
			<div class="date"><time></time></div>
			<p class="text"></p>
		</article>
	</div>
	<script type="text/javascript">
		enableTab("txt");
	</script>
{% endblock %}

web-noter/templates/api-info.html
{% extends "base.html" %}
{% block title %}API info{% endblock %}
{% block content %}
	<article class="note">
		<a href="/api-info/">
			<span class="title">How to use API</span>
		</a>
		<p class="text">
			With Noter API you can build apps that use this site.<br/>
			For example, you can write command line script that prints your last created note.<br/>
			<br/>
			API can be accessed by sending POST request on these URLs:
			<ul>
				<li>{% url "API:getNotes" %} - get notes of the user</li>
				<li>{% url "API:getNote" %} - get note by ID.</li>
				<li>{% url "API:rmNote" %} - remove note</li>
				<li>{% url "API:rmNotes" %} - remove multiple notes</li>
				<li>{% url "API:getUserInfo" %} - get account info</li>
				<li>{% url "API:addNote" %} - add single note</li>
				<li>{% url "API:addNotes" %} - add multiple notes</li>
				<li>{% url "API:register" %} - register</li>
				<li>{% url "API:deleteAccount" %} - delete account</li>
			</ul>
			Every URL requires username and password and returns JSON.
			
			<h3>Python example</h3>
			Let's say we want to get our notes.<br/>
			It means, that we need to send POST request to {% url "API:getNotes" %}.<br/>
			We will use <code>httplib</code> to do that.<br/>
			Here's the code:
			{% spaceless %}
				<pre><code>import httplib, json
from urllib import urlencode

headers = {
	'Content-type': "application/x-www-form-urlencoded",
	'Accept': "text/plain"
}

parameters = urlencode({
	'username': "guest",
	'password': "guest"
})

conn = httplib.HTTPConnection("web-noter.herokuapp.com") # Make HTTP connection
conn.request("POST", "{% url "API:getNotes" %}", parameters, headers) # Send request
response_obj = conn.getresponse() # Get response
response = response_obj.read() # Get string
conn.close() # Close connection
data = json.loads(response) # Convert JSON -&gt; list
print(data)</code>
				</pre>
			{% endspaceless %}
			<h3>Another Python example</h3>
			At this time we want to add new note.<br/>
			And we will have to send POST request to <code>{% url "API:addNote" %}</code>.<br/>
			Code:
			<pre><code>import httplib, json
from urllib import urlencode

headers = {
    'Content-type': "application/x-www-form-urlencoded",
    'Accept': "text/plain"
}

parameters = urlencode({
    'username': "guest",
    'password': "guest",
	'title': "Hello from Python!",
	'text': "Isn't it amazing?",
	'tags': "test, api",
	'type': "n" # Can be n(ote), t(odo), s(nippet) or w(arning)
})

conn = httplib.HTTPConnection("web-noter.herokuapp.com") # Make HTTP connection
conn.request("POST", "{% url "API:addNote" %}", parameters, headers) # Send request
response_obj = conn.getresponse() # Get response
response = response_obj.read() # Get string
conn.close() # Close connection
data = json.loads(response) # Convert JSON -&gt; dictionary
if data["success"]:
	print("Hurray!")
	print("ID of new note: {}".format(data["id"]))
else:
	print("Fail.")
	print("Message: %s" %data["message"])
</code>
</pre>
			You can use other URLs in similiar way.
		</p>
	</article>
{% endblock %}

web-noter/templates/base.html
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="utf-8" />
		<meta http-equiv="Content-Type" content="text/html" />
		<meta http-equiv="content-language" content="en" />
		<meta name="copyright" content="Ivan Konovalov" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta name="format-detection" content="telephone=no" />
		<title>{% block title %}{% endblock %} - Noter</title>
		<link rel="stylesheet" type="text/css" href="/static/css/style.min.css" />
		<link rel="shortcut icon" href="/static/img/Noter-logo.png" />
		<script type="text/javascript" src="/static/js/jquery-2.1.0.min.js"></script>
		<script type="text/javascript" src="/static/js/jquery.scrollTo.min.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/js/highlight.js/styles/mono-blue.css" />
		<script type="text/javascript" src="/static/js/highlight.js/highlight.pack.js"></script>
		<script type="text/javascript" src="/static/js/noter.min.js"></script>
		{% block head %}
		{% endblock %}
	</head>
	<body>
		<div id="progress-indicator"></div>
		{% include "include/header.html" %}
		<section id="main" role="main">
			<script type="text/javascript">
				onLoad();
			</script>
			<noscript>
				<h3>Please, enable JavaScript</h3>
			</noscript>
			{% block content %}
			{% endblock %}
		</section>	
		{% include "include/footer.html" %}		
	</body>
</html>

web-noter/templates/delete_account.html
{% extends "base.html" %}
{% block title %}Delete account{% endblock %}
{% block content %}
	<div class="margin-bottom">
		<div class="margin-bottom">
			<h1>Are you sure?</h1>
			<p>Your account will be deleted <strong>forever</strong>.</p>
		</div>
		<div class="margin-bottom">
			<form method="post" action="/delete-account/">
				{% csrf_token %}
				<div class="margin-bottom">
					<h4>Please enter your password to confirm</h4>
					<input type="password" placeholder="Your password" name="confirm" />
				</div>
				<div class="margin-bottom">
					<button class="btn-blue" type="submit">Delete account</button>
				</div>
			</form>
		</div>
	</div>
{% endblock %}